stages:
  - prepare
  - build

before_script:
  - cd $CI_PROJECT_NAME
  

prepare:
  stage: prepare
  tags:
    - faramir
  script:
    - ls -lh
    - gbp export-orig
    - dpkg-source -b .

build:
  stage: build
  tags:
    - faramir
  script:
    - sbuild --arch=amd64 --dist=parrot --no-run-lintian --arch-all --arch-any
    - sbuild --arch=i386 --dist=parrot --no-arch-all --arch-any --no-run-lintian --no-source || true
    - sbuild --arch=arm64 --dist=parrot --no-arch-all --arch-any --no-run-lintian --no-source || true
    - sbuild --arch=armhf --dist=parrot --no-arch-all --arch-any --no-run-lintian --no-source || true
    - rsync -Pahv ../*.{deb,udeb,,dsc,xz,gz,bz2,zip} /srv/repo-lts/incoming/ || true